# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: c:\titan\titan-address-api
  repository: c:\titan\titan-address-api
  name: titanaddressapi
  tag: latest
  pullPolicy: Always

global:
  siteId: ny80
  environmentId: et
  elasticsearch:
    host: ""
    port: 443
    protocol: "HTTPS"
    validateCertificate: false

observerFailures: 5
observerSuccesses: 1

logging:
  image:
    repository: ceresappuseast00.azurecr.io/logging-sidecar-dotnet:1.6
    tag: latest
    pullPolicy: Always
  index: "titan-titanaddressapi"

service:
  type: ClusterIP
  port: 5000

ingress:
  host: "webapi.local"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
